#!/usr/bin/env bash

# this script installs and configure nginx web server

apt-get update -y
apt-get install -y nginx

echo Hello world! > /var/www/html/index.html
echo Ceci n\'est pas une page > /var/www/html/404.html
ufw allow 'Nginx HTTP'
sed -i "/index.nginx-debian.html /a location \/redirect_me {\n\t\treturn 301 https:\/\/www.alxafrica.com/;\n\t}" /etc/nginx/sites-available/default
sed -i "/index.nginx-debian.html /a error_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html; \n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
service nginx restart
