#!/usr/bin/env bash

# this script installs and configures HAPROXY

apt-get -y update
apt-get install haproxy -y

FRONTEND="frontend www\n\tbind *:80\n\tmode http\n\tdefault_backend backend"
BACKEND="backend balancer\n\tserver web-01 18.234.129.142:80 check\n\tserver web-02 35.174.185.141:80 check"
sed -i "$ a$FRONTEND" /etc/haproxy/haproxy.cfg
sed -i "$ a$BACKEND" /etc/haproxy/haproxy.cfg
sed -i '$ a/#ENABLED=1/' /etc/default/haproxy
service haproxy restart
