#!/usr/bin/env bash
# this script tells a story about the users in /etc/passwd

while IFS=: read -r username passwd usid gid uidi direc shell; do
	echo "The user $username is part of the $gid gang, lives in $direc and rides $shell. $usid's place is protected by the passcode $passwd, more info about the user here: $uidi";
done < /etc/passwd
