#!/usr/bin/env bash
# This script parses apache log files and prints out
# IP address with HTTP status  code


awk '{print $1, $9}' ./apache-access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
