#!/usr/bin/env bash
# This code prints Best school in other iterations
# while bad luck for 4th iteration and good luck for
# 8th iteration

i=0
while [ $i -lt 10 ]; do
	if (("$i" == "3")); then
		echo "bad luck"
	elif (("$i" == "7")); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++));
done
